name: Sync from main aria-at-gh-actions-helper repo

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_PAT }}

      - name: Sync from original repo
        run: |
          # Save the current workflow file
          cp .github/workflows/sync.yml /tmp/sync.yml

          # Sync with upstream
          git remote add upstream https://github.com/bocoup/aria-at-gh-actions-helper.git
          git fetch upstream
          git reset --hard upstream/main

          # Restore the workflow file and push
          cp /tmp/sync.yml .github/workflows/sync.yml
          git push -f origin main
