name: Sync from main aria-at-gh-actions-helper repo

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_PAT }}

      - name: Sync from original repo
        run: |
          git remote add upstream https://github.com/bocoup/aria-at-gh-actions-helper.git
          git fetch upstream
          git reset --hard upstream/main
          git push -f origin main
